Remove MBEDTLS_ENTROPY_NV_SEED and MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
ARMmbed/mbed-os-example-attestation pull request #22
Opened 2019-08-15 16:46 UTC by devran01

Following changes are done,
1. Remove static private and public key and let attestation service
generate them
2. Remove MBEDTLS_ENTROPY_NV_SEED config option and relevant method
fake_set_initial_nvseed() used to inject fake NV seed
3. Remove MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES config option to utilize
Hardware TRNG available on K64F

Signed-off-by: Devaraj Ranganna <devaraj.ranganna@arm.com>

2019-08-15 16:46 UTC, devran01 commented
@Patater  Please review

2019-08-15 18:30 UTC, Patater commented
First commit needs breaking up, as it tries to do too much all at once. Each line item in the commit description should be its own commit.

2019-08-16 14:02 UTC, devran01 commented
@Patater done.

2019-08-20 10:31 UTC, jamesbeyond requested changes

2019-08-20 10:31 UTC, jamesbeyond commented on mbed_app.json
> +             "platform.stdio-baud-rate": 115200,
can you remove this line, and keep this default as 9600

2019-08-20 13:38 UTC, Patater commented
Could you remove the `1.` from the commit title of `1. Remove static private and public key and let attestation service`?

2019-08-21 08:49 UTC, devran01 commented
@jamesbeyond @Patater done

2019-08-23 14:10 UTC, jamesbeyond approved these changes
LGTM

2019-08-23 16:53 UTC, Patater approved these changes

2019-08-23 16:53 UTC, merged

2019-08-26 07:43 UTC, 0xc0170 commented
We suspect this broke Mbed OS master testing, see internal ticket MBEDOSTEST-726

2019-08-27 09:49 UTC, Patater commented on mbedtls_user_config.h
>  #   define MBEDTLS_PSA_INJECT_ENTROPY
We should remove `MBEDTLS_PSA_INJECT_ENTROPY` as well